src/app/routes/auth.py
from flask import Blueprint, render_template, request, redirect
from flask_login import login_user, logout_user, login_required, current_user
from passlib.hash import sha256_crypt
import pyotp
import qrcode
import io
import base64
from ..models import user_loader, DATABASE
from ..helpers import is_input_valid, count_entropy
import sqlite3
import time
from ..auth_limits import is_locked_out, reset_attempts, record_failed_attempt, DELAY_TIME
from Crypto.Cipher import AES
from Crypto import Random
from Crypto.Protocol.KDF import PBKDF2
from Crypto.PublicKey import RSA
from Crypto.Util.Padding import pad, unpad

auth_bp = Blueprint("auth", __name__)
GLOBAL_SECRET = b"206363ef77d567cc511df5098695d2b8"


@auth_bp.route("/", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("index.html")

    username = request.form.get("username")
    password = request.form.get("password")
    client_ip = request.remote_addr

    if is_locked_out(client_ip):
        return "Too many failed attempts. Try again later.", 403

    if not is_input_valid(username, val='username'):
        record_failed_attempt(client_ip)
        return "Invalid input for username", 401

    user = user_loader(username)

    if user is None or not sha256_crypt.verify(password, user.password):
        time.sleep(DELAY_TIME)
        record_failed_attempt(client_ip)
        return "Invalid username or password", 401

    code = request.form.get("code")
    if not is_input_valid(code, val='code'):
        time.sleep(DELAY_TIME)
        record_failed_attempt(client_ip)
        return "Invalid input for 2FA", 401

    totp_enc = user.totp
    iv = totp_enc[:AES.block_size]
    cipher = AES.new(GLOBAL_SECRET, AES.MODE_CBC, iv)
    totp_dec = cipher.decrypt(totp_enc[AES.block_size:]).decode('utf-8')

    totp = pyotp.TOTP(totp_dec)
    if not totp.verify(code):
        time.sleep(DELAY_TIME)
        record_failed_attempt(client_ip)
        return "Invalid 2FA code", 401

    reset_attempts(client_ip)
    login_user(user)
    return redirect("/hello")


@auth_bp.route("/logout")
def logout():
    logout_user()

    return redirect("/")


@auth_bp.route("/change_password", methods=["GET", "POST"])
@login_required
def change_password():
    if request.method == "GET":
        return render_template("change_password.html")

    current_password = request.form.get("current_password")
    new_password = request.form.get("new_password")
    code = request.form.get("code")

    if not is_input_valid(code, val='code'):
        return "Invalid input for 2FA", 403

    user = current_user

    if not sha256_crypt.verify(current_password, user.password):
        time.sleep(DELAY_TIME)
        return "Current password is incorrect", 403

    totp_enc = user.totp
    iv = totp_enc[:AES.block_size]
    key = PBKDF2(current_password, user.salt)
    cipher = AES.new(GLOBAL_SECRET, AES.MODE_CBC, iv)
    totp_dec = cipher.decrypt(totp_enc[AES.block_size:]).decode('utf-8')

    cipher = AES.new(key, AES.MODE_CBC, iv)
    prv_key_dec = cipher.decrypt(user.prv_key)

    totp = pyotp.TOTP(totp_dec)
    if not totp.verify(code):
        time.sleep(DELAY_TIME)
        return "Invalid 2FA token", 403

    hashed_password = sha256_crypt.hash(new_password)

    new_key = PBKDF2(new_password, user.salt)
    cipher = AES.new(GLOBAL_SECRET, AES.MODE_CBC, iv)
    totp_enc = iv + cipher.encrypt(totp_dec.encode())

    cipher = AES.new(new_key, AES.MODE_CBC, iv)
    prv_key_enc = cipher.encrypt(prv_key_dec)

    db = sqlite3.connect(DATABASE)
    cursor = db.cursor()
    cursor.execute(
        "UPDATE user SET password = ?, totp_secret = ?, prv_key = ? WHERE username = ?",
        (hashed_password, totp_enc, prv_key_enc, user.id)
    )
    db.commit()

    return redirect("/hello")


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")

    username = request.form.get("username")
    password = request.form.get("password")

    if not is_input_valid(username, val='username'):
        return "Invalid input for username", 401

    if count_entropy(password) < 60:
        return "Your password is too weak.", 401

    hashed_password = sha256_crypt.hash(password)
    totp_secret = pyotp.random_base32()

    iv = Random.new().read(AES.block_size)
    salt = Random.new().read(16)
    key = PBKDF2(password, salt)

    cipher = AES.new(GLOBAL_SECRET, AES.MODE_CBC, iv)
    totp_enc = iv + cipher.encrypt(totp_secret.encode())

    rsa_keys = RSA.generate(2048)
    pub_key = rsa_keys.public_key().exportKey()
    prv_key = pad(rsa_keys.exportKey(), AES.block_size)

    cipher = AES.new(GLOBAL_SECRET, AES.MODE_CBC, iv)
    prv_key_enc_1 = cipher.encrypt(prv_key)
    cipher = AES.new(key, AES.MODE_CBC, iv)
    prv_key_enc_2 = cipher.encrypt(prv_key_enc_1)

    db = sqlite3.connect(DATABASE)
    cursor = db.cursor()

    try:
        cursor.execute(
            "INSERT INTO user (username, password, salt, totp_secret, pub_key, prv_key) VALUES (?, ?, ?, ?, ?, ?)",
            (username, hashed_password, salt, totp_enc, pub_key, prv_key_enc_2)
        )
        db.commit()
    except sqlite3.IntegrityError:
        return "User already exists", 403

    totp = pyotp.TOTP(totp_secret)
    provisioning_uri = totp.provisioning_uri(username, issuer_name="SafeAPP")
    qr_img = qrcode.make(provisioning_uri)

    buffer = io.BytesIO()
    qr_img.save(buffer, format="PNG")
    buffer.seek(0)
    qr_code_base64 = base64.b64encode(buffer.read()).decode("utf-8")

    return render_template(
        "qr_code.html", qr_code=qr_code_base64, totp_secret=totp_secret
    )

src/app/routes/main.py
from base64 import b64encode
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
import sqlite3
import markdown
from ..models import DATABASE
import bleach
from ..helpers import is_input_valid
from Crypto.Signature import pkcs1_15
from Crypto.Cipher import AES
from Crypto.PublicKey import RSA
from Crypto.Protocol.KDF import PBKDF2
from Crypto.Hash import SHA256
from passlib.hash import sha256_crypt
from Crypto.Util.Padding import unpad
from ..auth_limits import DELAY_TIME
import time
from .auth import GLOBAL_SECRET

main_bp = Blueprint("main", __name__)

ALLOWED_TAGS = {
    "h1",
    "h2",
    "h3",
    "p",
    "img",
    "a",
    "b",
    "blockquote",
    "code",
    "em",
    "i",
    "li",
    "ol",
    "strong",
    "ul",
    'br'
}
ALLOWED_ATTRIBUTES = {
    "a": ["href", "title"],
    "img": ["src", "alt", "title"],
}


@main_bp.route("/hello", methods=["GET"])
@login_required
def hello():
    username = current_user.id
    db = sqlite3.connect(DATABASE)
    cursor = db.cursor()
    cursor.execute(
        "SELECT username, feed, sign, hashed_feed, feed_date FROM feeds ORDER BY feed_date DESC"
    )
    all_feeds = cursor.fetchall()

    sanitized_feeds = [
        (
            feed[0],
            bleach.clean(feed[1], tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES),
            feed[2],
            feed[3],
            feed[4],
        )
        for feed in all_feeds
    ]

    return render_template("hello.html", username=username, all_feeds=sanitized_feeds)


@main_bp.route("/render", methods=["POST"])
@login_required
def render():
    md = request.form.get("markdown", "")
    password = request.form.get("password")

    if not sha256_crypt.verify(password, current_user.password):
        time.sleep(DELAY_TIME)
        return "Incorrect password", 403

    if not is_input_valid(md):
        return "Invalid input.", 401

    rendered = markdown.markdown(md, extensions=['nl2br'])
    username = current_user.id

    rendered_safe = bleach.clean(
        rendered, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES
    )

    prv_key = current_user.prv_key
    iv = current_user.totp[:AES.block_size]
    key = PBKDF2(password, current_user.salt)
    cipher = AES.new(key, AES.MODE_CBC, iv)
    prv_key_dec_1 = cipher.decrypt(prv_key)
    cipher = AES.new(GLOBAL_SECRET, AES.MODE_CBC, iv)
    prv_key_dec_2 = unpad(cipher.decrypt(prv_key_dec_1), AES.block_size)

    rsa_keys = RSA.importKey(prv_key_dec_2)

    rendered_hash = SHA256.new(rendered_safe.encode())
    sign = pkcs1_15.new(rsa_keys).sign(rendered_hash)
    sign_b64 = b64encode(sign)
    rendered_hash_b64 = b64encode(rendered_hash.digest())

    db = sqlite3.connect(DATABASE)
    cursor = db.cursor()
    cursor.execute(
        "INSERT INTO feeds (username, feed, sign, hashed_feed) VALUES (?, ?, ?, ?)",
        (username, rendered_safe, sign_b64, rendered_hash_b64)
    )
    db.commit()
    return render_template("markdown.html", rendered=rendered_safe)

src/app/routes/user_page.py
from flask import Blueprint, render_template
from ..models import DATABASE
import sqlite3
from .main import ALLOWED_TAGS, ALLOWED_ATTRIBUTES
import bleach

user_bp = Blueprint("user_page", __name__)


@user_bp.route("/user/<user_id>", methods=["GET"])
def user_page(user_id):
    db = sqlite3.connect(DATABASE)
    cursor = db.cursor()
    cursor.execute(
        "SELECT username, feed, sign, hashed_feed, feed_date FROM feeds WHERE username == ? ORDER BY feed_date DESC",
        (user_id,)
    )
    user_feeds = cursor.fetchall()

    sanitized_feeds = [
        (
            feed[0],
            bleach.clean(feed[1], tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES),
            feed[2],
            feed[3],
            feed[4],
        )
        for feed in user_feeds
    ]

    print(user_feeds)

    cursor.execute(
        "SELECT pub_key FROM user WHERE username == ?",
        (user_id,)
    )
    pub_key = cursor.fetchall()[0][0]

    return render_template("user_page.html", username=user_id, user_feeds=sanitized_feeds, pub_key=pub_key)

src/app/templates/change_password.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Change Password</title>
</head>
<body>
<h1>Change Password</h1>
<form method="post" action="{{ url_for('auth.change_password') }}">
    <label for="current_password">Current Password:</label><br>
    <input type="password" id="current_password" name="current_password" required><br><br>

    <label for="new_password">New Password:</label><br>
    <input type="password" id="new_password" name="new_password" required><br><br>

    <label for="code">2FA Token:</label><br>
    <input type="text" id="code" name="code" required><br><br>

    <input type="submit" value="Change Password">
</form>
</body>
</html>

src/app/templates/hello.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Feed</title>
    <style>
        .username-link {
            text-decoration: none;
            color: black;
            font-weight: bold;
            cursor: pointer;
            font-size: 20px;
        }
        .username-link:hover {
            color: blue;
        }
        .feed-content {
            word-wrap: break-word;
            overflow-wrap: break-word;
            max-width: 100%;
        }
    </style>
</head>
<body>
<h1>Hello {{ username }}!</h1>
<form action="{{ url_for('auth.change_password') }}">
  <input type="submit" value="Change Password" />
</form>
<form action="{{ url_for('auth.logout') }}">
  <input type="submit" value="Log out" />
</form>

<form action="{{ url_for('main.render') }}" method="post">
  <label for="markdown">Share something:</label><br>
  <textarea id="markdown" name="markdown" rows="5" cols="50"></textarea><br>
  <label for="password">Password: </label>
  <input type="password" id="password" name="password" required><br>
  <input type="submit" value="Post">
</form>

<h1>Feed</h1>
{% for feed in all_feeds %}
    <div>
            <hr>
            <p>
                <a href="{{ url_for('user_page.user_page', user_id=feed[0]) }}" class="username-link"><strong>{{ feed[0] }}</strong></a>
                <em>{{ feed[4] }}</em><br>{{ feed[1]|safe }}
            </p><br><br>
            <p class="feed-content">
                <strong>Hashed feed (in base64, SHA256):</strong><br>
                {{ feed[3] }}
            </p>
            <p class="feed-content">
                <strong>Signature (in base64):</strong><br>
                {{ feed[2] }}
            </p>
        </div>
    </div>
{% endfor %}
</body>
</html>

src/app/templates/index.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h1>Login</h1>
<form action="{{ url_for('auth.login') }}" method="post">
  <label for="username">Username: </label>
  <input type="text" id="username" name="username" required><br>
  <label for="password">Password: </label>
  <input type="password" id="password" name="password" required><br>
  <label for="code">2FA Code:</label>
  <input type="text" id="code" name="code" required><br>
  <input type="submit" value="Submit">
</form>

<p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register here</a>.</p>

</body>
</html>

src/app/templates/markdown.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Markdown</title>
</head>
<body>
<h1> You posted: </h1>
{{ rendered | safe}}
<br>
<form action="{{ url_for('main.hello') }}">
  <input type="submit" value="Go back" />
</form>
</body>
</html>

src/app/templates/qr_code.html
<html>
<head>
    <title>QR Code</title>
</head>
<body>
    <h1>Setup Two-Factor Authentication</h1>
    <p>You have to scan this QR code with your authenticator app to login.</p>
    <img src="data:image/png;base64,{{ qr_code }}" alt="QR Code">
    <p>If you cannot scan the QR code, use this code: <strong>{{ totp_secret }}</strong></p>
    <a href="/">Go to Login</a>
</body>
</html>

src/app/templates/register.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form action="{{ url_for('auth.register') }}" method="POST">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Register</button>
    </form>
    <a href="/">Back to login</a>
</body>
</html>

src/app/templates/user_page.html
<html>
<head>
    <meta charset="UTF-8">
    <title>User Page - {{ username }}</title>
    <style>
        .username {
            color: black;
            font-weight: bold;
            font-size: 20px;
        }
        .feed-content {
            word-wrap: break-word;
            overflow-wrap: break-word;
            max-width: 100%;
        }
    </style>
</head>
<body>
<form action="{{ url_for('main.hello') }}">
  <input type="submit" value="Back to Home" />
</form>

<h1>{{ username }}</h1>
<div class="feed-content"><strong>User Public Key:</strong><br>{{ pub_key }}</div><br><br>
<h2>{{ username }}'s Posts</h2>
{% if user_feeds %}
    {% for feed in user_feeds %}
        <div>
            <hr>
            <p>
                <strong>{{ feed[0] }}</strong>
                <em>{{ feed[4] }}</em><br>{{ feed[1]|safe }}
            </p><br><br>
            <p class="feed-content">
                <strong>Hashed feed (in base64, SHA256):</strong><br>
                {{ feed[3] }}
            </p>
            <p class="feed-content">
                <strong>Signature (in base64):</strong><br>
                {{ feed[2] }}
            </p>
        </div>
    {% endfor %}
{% endif %}
</body>
</html>